# -*- mode: ruby -*-
# vi: set ft=ruby :

#------------------------------------------------------------------------------
# VM Environment and parameter configuration
# These settings can be overridden by creating a file named Vagrantfile.local
#------------------------------------------------------------------------------
vm_define="solarnet"
bootstrap_path="bootstrap.sh"
vm_name="SolarNet Dev"
basebox_name="ubuntu/jammy64"
no_of_cpus=1
memory_size=2048
vm_gui=true

git_branch="develop"
git_repos="build external common central node"
postgres_version=12
java_version="8 11 17"
solarnet_host="solarnetworkdev.net"

# Note xserver-xorg-legacy was only way I could find to get X to start as solardev on login from console
desktop_packages="xorg xserver-xorg-legacy xserver-xorg-video-vesa xserver-xorg-video-vmware xfonts-scalable fluxbox eterm xfonts-terminus virtualbox-guest-utils virtualbox-guest-x11 pgadmin4-desktop xterm --no-install-recommends"

# Read any user specific configuration overrides - cater for this file not existing
local_env_config_file="Vagrantfile.local"
begin
  localsettings = File.read local_env_config_file
  eval localsettings
  rescue Errno::ENOENT
    #print "No "+local_env_config_file+" found\n"
end

# Check for required plugin
unless Vagrant.has_plugin?("vagrant-disksize")
  puts 'vagrant-disksize plugin is required. To install run: `vagrant plugin install vagrant-disksize`'
  abort
end

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.vm.define vm_define

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = basebox_name

  # Use the https://github.com/sprotheroe/vagrant-disksize plugin
  config.disksize.size = '10GB'

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=755"]
  config.vm.synced_folder "../../bin", "/vagrant/bin", :mount_options => ["dmode=755"]
  config.vm.synced_folder "../../conf", "/vagrant/conf", :mount_options => ["dmode=755"]
  config.vm.synced_folder "../../eclipse", "/vagrant/eclipse", :mount_options => ["dmode=755"]

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine (set to false if not installing desktop packages)
    vb.gui = vm_gui
    vb.memory = memory_size
    vb.cpus = no_of_cpus
    vb.name = vm_name
  end
  
  prov_args = [];
  if !java_version.to_s.empty?
    prov_args.push('-j', java_version.to_s)
  end
  if !postgres_version.to_s.empty?
    prov_args.push('-p', postgres_version.to_s)
  end
  if !solarnet_host.empty?
    prov_args.push('-h', solarnet_host)
  end
  if !git_branch.empty?
    prov_args.push('-b',  git_branch)
  end
  if !git_repos.empty?
    prov_args.push('-r', git_repos)
  end
  if vm_gui
    prov_args.push('-U', desktop_packages)
  end

  config.vm.provision :shell, path: bootstrap_path, :args => prov_args
end
